"""Adicionar colune 'line_position' ao modelo DataForm

Revision ID: 4c7d3a980b77
Revises: 
Create Date: 2024-05-10 11:04:23.924353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7d3a980b77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_position', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_form', schema=None) as batch_op:
        batch_op.drop_column('line_position')

    # ### end Alembic commands ###
